# Generated by Django 4.2.5 on 2024-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitch_arsenal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitcharsenalpitchnote",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
