# Generated by Django 4.2.5 on 2023-10-07 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitativeassessmentchoices",
            name="description",
            field=models.TextField(default="None"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assessment",
            name="unit",
            field=models.CharField(
                blank=True, default="None", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="creation_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
