# Generated by Django 4.2.5 on 2023-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_qualitativeassessmentchoices_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualitativeassessmentchoices",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
