# Generated by Django 4.2.5 on 2023-10-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_qualitativeassessmentchoices_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
