# Generated by Django 4.2.5 on 2023-10-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_assessment_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="unit",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
