# Generated by Django 4.2.5 on 2023-10-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_assessment_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drill",
            name="video_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
