# Generated by Django 4.2.5 on 2023-10-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_alter_drill_video_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drill", old_name="video_url", new_name="url",
        ),
    ]
