# Generated by Django 4.2.5 on 2023-11-20 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_rename_video_url_drill_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitativeassessmentscore",
            name="did_not_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quantitativeassessmentscore",
            name="did_not_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="qualitativeassessmentchoices",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="reports.assessment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qualitativeassessmentchoices",
            unique_together={("assessment", "choice")},
        ),
    ]
