# Generated by Django 4.2.5 on 2023-12-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_qualitativeassessmentscore_did_not_test_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateAssessmentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.assessment",
                        verbose_name="assessment",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reporttemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={"unique_together": {("template", "assessment")},},
        ),
    ]
